# Site
title: Sunny Days
description: Better than I was yesterday!
baseurl: ""

#Jekyll
permalink: /:categories/:title
author: "Sunny"
plugins:
  - jekyll-feed

sass:
  sass_dir: _sass
  style: compressed

defaults:
  - scope:
      path: ""
    values:
      layout: "post"

#Social
email: in.wise.nature@gmail.com
github_username: Sunn-y
